export const strip = (
  file,
  {
    frames = 6,
    frameMs = 150,
    loop = true,
    width = 72,
    height = 80,
    imageSmoothing = true,
    framePaddingX = 0,
    sourceFrameWidth = null,
    sourceFrames = null,
    retreatFrames = 0,
    retreatX = 0,
    anchorX = 0.5,
    anchorY = 0.93,
    groundY = null,
    sourceAssetWidth = file?.endsWith(".webp") ? 2172 : null,
    sourceAssetHeight = file?.endsWith(".webp") ? 724 : null,
  } = {},
) => ({
  file,
  frames,
  frameMs,
  loop,
  width,
  height,
  imageSmoothing,
  framePaddingX,
  sourceFrameWidth,
  sourceFrames,
  sourceAssetWidth,
  sourceAssetHeight,
  retreatFrames,
  retreatX,
  anchorX,
  anchorY,
  groundY,
});
